name: pemrograman_pert3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/showroom.jpg
    - assets/car1.jpg
    - assets/car2.jpg
    - assets/car3.jpg
    - assets/car4.jpg
